// Mocks generated by Mockito 5.0.17 from annotations
// in test_selecti/test/widget_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'widget_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MockitoTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockitoTest extends _i1.Mock implements _i2.MockitoTest {
  MockMockitoTest() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MockitoTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockitoExampleRelaxed extends _i1.Mock implements _i2.MockitoTest {}
